# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: ai94iq.ClipShelf
PackageVersion: 0.3.3
InstallerType: wix
Scope: machine
UpgradeBehavior: install
ProductCode: '{AF3D81B5-8D0D-4FA0-8B9E-F06EDC8F786E}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ai94iq/ClipShelf/releases/download/v0.3.3/ClipShelf-Setup-0.3.3.msi
  InstallerSha256: 14C321F057318D2D668B804FBABE012E88372D06A5492AFBC51E252781586EDE
ManifestType: installer
ManifestVersion: 1.6.0
